# Generated by Django 6.0.3 on 2026-05-09 13:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cadastro_projeto', '0002_alter_perfilusuario_options_perfilusuario_ativo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjetoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('categoria', models.CharField(blank=True, max_length=100)),
                ('semestre', models.CharField(blank=True, max_length=20)),
                ('nota', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('em_avaliacao', 'Em Avaliação'), ('aprovado', 'Aprovado'), ('reprovado', 'Reprovado')], default='em_avaliacao', max_length=20)),
                ('tags', models.CharField(blank=True, help_text='Separe por vírgula. Ex: React,Node.js', max_length=200)),
                ('link_repositorio', models.URLField(blank=True, null=True)),
                ('link_demo', models.URLField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, null=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projetos_usuario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
    ]
