# Generated by Django 6.0.3 on 2026-06-05 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cadastro_projeto', '0003_projetousuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projetousuario',
            name='nota',
        ),
        migrations.AddField(
            model_name='projetousuario',
            name='comentario',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projetousuario',
            name='conceito',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
