# Generated by Django 6.0.3 on 2026-06-05 15:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cadastro_projeto', '0004_remove_projetousuario_nota_projetousuario_comentario_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logatividade',
            options={'ordering': ['-data']},
        ),
        migrations.AlterField(
            model_name='projetousuario',
            name='conceito',
            field=models.CharField(blank=True, choices=[('A', 'A - Excelente'), ('B', 'B - Muito Bom'), ('C', 'C - Regular'), ('D', 'D - Insuficiente')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='projetousuario',
            name='tags',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_fantasia', models.CharField(max_length=200)),
                ('cnpj', models.CharField(max_length=18, unique=True)),
                ('area_atuacao', models.CharField(blank=True, max_length=100)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='empresa', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
