# Generated by Django 6.0.3 on 2026-06-05 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cadastro_projeto', '0005_alter_logatividade_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logatividade',
            options={'ordering': ['-data'], 'verbose_name': 'Log de Atividade', 'verbose_name_plural': 'Logs de Atividades'},
        ),
        migrations.RemoveField(
            model_name='projetousuario',
            name='comentario',
        ),
        migrations.RemoveField(
            model_name='projetousuario',
            name='conceito',
        ),
        migrations.AddField(
            model_name='projetousuario',
            name='nota',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projetousuario',
            name='tags',
            field=models.CharField(blank=True, help_text='Separe por vírgula. Ex: React,Node.js', max_length=200),
        ),
        migrations.DeleteModel(
            name='Empresa',
        ),
    ]
