# Generated by Django 6.0.3 on 2026-06-08 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cadastro_projeto', '0011_curriculo_encerramento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projetousuario',
            name='conceito',
            field=models.CharField(blank=True, choices=[('Excelente', 'Excelente'), ('Ótimo', 'Ótimo'), ('Bom', 'Bom'), ('Suficiente', 'Suficiente'), ('Insuficiente', 'Insuficiente')], max_length=20, null=True),
        ),
    ]
