# Generated by Django 6.0.3 on 2026-06-08 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_cadastro_projeto', '0013_topicoforum_privado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topicoforum',
            name='privado',
        ),
    ]
